config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie_id = params[:bookmark][:movie_id]
    @bookmark.list = @list
    @bookmark.save!
  end

  def destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    # @list.bookmarks = @bookmarks
   @list.save!
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :overview, :poster_url, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmark new</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Create bookmark", class: "btn btn-primary" %>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="banner" data-controller="navbar" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Save any kind of movies</strong>!</h1>
    <p>Classic</p>
  </div>
</div>


 <% @lists.each do |list| %>
  <p>
    <strong>Name:</strong>
    <h2><%= link_to list.name, list_path(list) %></h2>
  <p>

  <% end %>
<%= link_to "Create a list", new_list_path(@list) %>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>
<div class="container text-center">
<div style="height:300px; widht:300px; background-size:cover; background-image:url('<%= cl_image_path @list.photo.key %>')">

<h2><%= @list.name %></h2>

  <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>

</div>

<%= link_to "Create a bookmark",  new_list_bookmark_path(@list) %>


<%= link_to "All Lists", lists_path %>
</div>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :overview %>
    <%= f.input :poster_url %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Overview:</strong>
    <%= movie.overview %>
  </p>

  <p>
    <strong>Poster url:</strong>
    <%= movie.poster_url %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "Create a list", new_list_path(@list) %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>

  <%= link_to "Back to movies", movies_path %>


</div>